{
	"_comment":"字母部分标识识别类型;数字为对应的端口号; 0为默认的无效值，如需修改，则将数字0更改为对应的端口号即可",
	
	"_comment_": "设备缺陷识别类型",
    "rydd": 25806,
    "wcgz": 25807,
    "hzyw": 25800,
    "xdwcr": 25810,
    "yw_nc": 25809,
    "claqgk": 25808,
    "ryjjph": 25803,
    "ywrq": 25802,
    "wtyl": 25802,
    "wtyc": 25802,
    "ryrq": 25804,
    "yxcr": 25805,
    "wcaqm": 25801,

    "bj_bpmh": 0,
    "bj_bpps": 0,
    "bj_wkps": 0,
    "jyz_pl": 0,
    "sly_bjbmyw": 0,
    "sly_dmyw": 0,
    "jsxs": 0,
    "hxq_gjtps": 0,
    "xmbhyc": 0,
    "yw_gkxfw": 0,
    "mcqdmsh": 0,
    "gbps": 0,
    "gjptwss": 0,
    "bmwh": 0,
    "xy": 0,
    "bjdsyc": 0,
    "ywzt_yfyc": 0,
    "hxq_gjbs": 0,
    "kgg_ybh": 0,
    "kgg_ybf": 0,
    "dthtps": 0,
    "yxdghsg": 0,
    "wpdaqs": 0,
    "sndmjs": 0,
    "qmls": 0,
    "wdls": 0,
    "ywzt_ywzsjyc": 0,
    "hxq_yfps": 0,
    "dxdg": 0,
    "sly_jhbyw": 0,
    "hkgnl": 0,
    "pzqcd": 0,
    "drqgd": 0,

	"__comment": "设备状态识别",
    "isolator": 0,
    "switch": 0,
    "meter": 0,
    "infrared": 0,
    "sound": 0,
    "light": 0,
    "qrcode": 0,
	
	"__comment__": "设备缺陷判别类型",
    "tx_pd": 0,
    "tx_yzwpy": 0
}